# Generated by Django 5.2.3 on 2025-06-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_categoriaartigogaleria_artigogaleria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigogaleria',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
