# Generated by Django 5.2.3 on 2025-06-25 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_artigogaleria_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigogaleria',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
