# Generated by Django 5.2.3 on 2025-06-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_artigogaleria_datahora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigogaleria',
            name='datahora',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
