# Generated by Django 5.2.3 on 2025-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_artigogaleria_datahora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigogaleria',
            old_name='image_path',
            new_name='imagem_path',
        ),
        migrations.AddField(
            model_name='artigogaleria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/%Y/%m/%d'),
        ),
    ]
